### PR TITLE
Removed log files that snuck into last commit

### PR DESCRIPTION
**Pull request by thelmuth**

### CODE REVIEW

**Comment by Vaguery** [comment]
Would it be too risky or inconvenient to put lines like `*.csv` and `*.json` into `.gitignore`?

**Comment by thelmuth** [comment]
Yes, that sounds like a good idea. Let me go update this pull request.

The only problem I could see this causing would be if there were a csv data file read by a problem, we'd be confused until we remembered about the .gitignore. But, we already have one of those, and just use a .txt extension.

**Comment by thelmuth** [comment]
Ok, should be ready to go now.

**Comment by lspector** [comment]
Done.

**Pull request merged**
