### PR TITLE
Record runs

### PR DESCRIPTION
**Pull request by saulshanabrook**
All this needs to happen before I encourage anyone to start trying this out:

- [x] get new schemas working
  - [x] check to make sure can take clojush schema
  - [x] change adding values to support, maybe using spec and multimethods (forget about speed)
  - [x] switch clojush code to support
  - [x] speed up!
- [x] get working with HDSF
  - [x] make sure hdfs deploys ok
  - [x] change tests to use it
  - [x] try on real run
  - [x] instead of writing to HDFS, write to local filesystem and copy (profile this)
- [x] create example queries:
  - [x] overview of runs: `uuid`, `problem-file`, `name`, `generation`, `status`
  - [x] overview of one run: given `uuid` -> `index`, `best-error` `best-generalization-error`
  - [x] replicate [amps results](https://push-language.hampshire.edu/t/amps-results/785)
- [ ] Write documentation about rational and how to use on discourse or here]
- [x] try with parquet version 2 file
- [x] remove `proto-repl-sayid` deps
- [ ] add command line field to make this optional
- [x] try v2 on spark and see if that works
- [x] deploy default spark w/ jupyter instance on docker
  - [ ] move reusable stuff to another notebook
- [x] add time (waiting on https://github.com/apache/spark/pull/15332)
- [ ] change to 0mq
- [ ] move clojure code back to `ici-recorder`
- [ ] extract spark generation to seperate file
- [ ] add test sending JSON data and running it processing in spark

### CODE REVIEW

**Comment by lspector** [comment]
Just to clarify before I merge:

- None of this will have any effect (including re: outputs produced) if `run` is called with default args?

- I don't need to worry about that "All checks have failed" business above?

**Comment by saulshanabrook** [comment]
Don't merge yet! I just put this up to be public about my progress, but I want to check off all those things in my todo first before merging.

**Comment by lspector** [comment]
Ah, thanks. Maybe for future PRs like this make that status a little more obvious for me?

**Comment by saulshanabrook** [comment]
Sure, the WIP in the title means "work in progress" aka not ready yet

**Comment by lspector** [comment]
Ah! Great & thanks for cluing me in.

**Comment by saulshanabrook** [comment]
@lspector OK if I merge this once the tests pass? 

I tried to be as minimally invasive to the code base as possible. There is still some progress to make on this ([as documented on discourse](Next progress is documented at https://push-language.hampshire.edu/t/recording-and-analyzing-experimental-results/830)], but I think this is in a good enough shape to merge. I have been using this branch and it has been working out.

**Pull request merged**
