### PR TITLE
Add automatic Clojush releases on every travis build

### PR DESCRIPTION
**Pull request by saulshanabrook**
This is what you should do (in this order)

1. Make sure your `LEIN_PASSWORD`, `LEIN_USERNAME`, and `GITHUB_TOKEN` env variables are in the [travis env variables settings](https://travis-ci.org/saulshanabrook/Clojush/settings)
2. Then click "Merge"

It will:

1. Build docs + push those to `gh-pages` branch after every master branch build
2. Run `lein release` as well those builds. This will:
    1. create new git commit and tag for new commit w/ out `-SNAPSHOT` in it
    2. Create jar and push that to clojars
    3. bump release number to next minor version
    4. Push new commits + tag back to github

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@lspector ready for you!

**Comment by saulshanabrook** [comment]
@lspector Just started looking at this again. I realized that we need your clojars credentials added to https://travis-ci.org/lspector/Clojush/settings before this will work (because it needs to have permission to publish a new version of the package).

**Comment by lspector** [comment]
As an environment variable? I see how to add name/value pairs but for this I would need at least some indication that it's about clojars, an ID, and a password, right? I'm not seeing where this should go.


> On Dec 7, 2015, at 8:38 AM, Saul Shanabrook <notifications@github.com> wrote:
> 
> @lspector <https://github.com/lspector> Just started looking at this again. I realized that we need your clojars credentials added to https://travis-ci.org/lspector/Clojush/settings <https://travis-ci.org/lspector/Clojush/settings> before this will work (because it needs to have permission to publish a new version of the package).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/pull/174#issuecomment-162526672>.
> 

--
Lee Spector, Professor of Computer Science
Acting Dean, School of Cognitive Science
Director, Institute for Computational Intelligence
Hampshire College, Amherst, Massachusetts, USA
lspector@hampshire.edu, http://hampshire.edu/lspector/, 413-559-5352

**Comment by saulshanabrook** [comment]
@lspector Yeah an environmental variable `LEIN_USERNAME ` for your clojar username and `LEIN_PASSWORD` for your password.

**Comment by lspector** [comment]
Done.

Seems odd that it would be LEIN rather than CLOJARS, or something like that, but I've done it...

 -Lee



> On Dec 8, 2015, at 4:05 PM, Saul Shanabrook <notifications@github.com> wrote:
> 
> @lspector <https://github.com/lspector> Yeah an environmental variable LEIN_USERNAME for your clojar username and LEIN_PASSWORD for your password.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/pull/174#issuecomment-163017490>.
> 

--
Lee Spector, Professor of Computer Science
Acting Dean, School of Cognitive Science
Director, Institute for Computational Intelligence
Hampshire College, Amherst, Massachusetts, USA
lspector@hampshire.edu, http://hampshire.edu/lspector/, 413-559-5352

**Comment by saulshanabrook** [comment]
Thanks @lspector! Yeah [lein has it just set to use those](https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#credentials-in-the-environment)

**Comment by saulshanabrook** [comment]
@lspector I think this worked! Two commits were created automatically, for bumping the version and then to the next snapshot version:
screen shot 2015-12-08 at 4 52 25 pm


And there was a [git tag](https://github.com/lspector/Clojush/releases/tag/v2.0.41) and a release to clojars

screen shot 2015-12-08 at 4 53 36 pm

**Comment by lspector** [comment]
:+1:

**Pull request merged**
