### PR TITLE
CSV for clustering

### PR DESCRIPTION
**Pull request by thelmuth**
Cleaned up the CSV printing significantly. Also, added UUIDs to every individual, and added tracking of parent UUIDs and the genetic operators used to create each individual.

This code solves issue #109

### CODE REVIEW

**Comment by lspector** [comment]
Tried to go through the update procedure on this one and got stuck. Please fix/advise. Transcript below.
---
MacBook-Pro:clojush leespector$ git checkout master
Switched to branch 'master'
MacBook-Pro:clojush leespector$ git fetch thelmuth
remote: Counting objects: 46, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 46 (delta 23), reused 0 (delta 0)
Unpacking objects: 100% (46/46), done.
From github.com:thelmuth/Clojush
   429af74..a9d14db  csv-for-clustering -> thelmuth/csv-for-clustering
   7c66111..6318f08  program-synthsis-benchmark-suite -> thelmuth/program-synthsis-benchmark-suite
MacBook-Pro:clojush leespector$ git merge thelmuth/csv-for-clustering
Updating 6318f08..a9d14db
Fast-forward
 project.clj                                     |    2 +
 src/clojush/individual.clj                      |   17 ++++---
 src/clojush/problems/demos/odd_csv_and_json.clj |    1 +
 src/clojush/pushgp/breed.clj                    |   17 ++++--
 src/clojush/pushgp/pushgp.clj                   |    1 +
 src/clojush/pushgp/report.clj                   |   65 ++++++++++------------
 6 files changed, 56 insertions(+), 47 deletions(-)
MacBook-Pro:clojush leespector$ git add .
MacBook-Pro:clojush leespector$ git commit -m "thelmuth/csv-for-clustering"
[master 087b807] thelmuth/csv-for-clustering
 1 files changed, 1 insertions(+), 1 deletions(-)
MacBook-Pro:clojush leespector$ git tag -a v2.0.16 -m "thelmuth/csv-for-clustering"
MacBook-Pro:clojush leespector$ git push origin master
Counting objects: 97, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (65/65), done.
Writing objects: 100% (73/73), 7.62 KiB, done.
Total 73 (delta 56), reused 0 (delta 0)
To git@github.com:lspector/Clojush.git
   6318f08..087b807  master -> master
MacBook-Pro:clojush leespector$ git push origin --tags
Counting objects: 1, done.
Writing objects: 100% (1/1), 179 bytes, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:lspector/Clojush.git
 * [new tag]         v2.0.16 -> v2.0.16
MacBook-Pro:clojush leespector$ lein clean
MacBook-Pro:clojush leespector$ lein jar
Warning: specified :main without including it in :aot. 
Implicit AOT of :main will be removed in Leiningen 3.0.0. 
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Compiling clojush.core
Release versions may not depend upon snapshots. 
Freeze snapshots to dated versions or set the LEIN_SNAPSHOTS_IN_RELEASE environment variable to override.
MacBook-Pro:clojush leespector$ lein pom
Release versions may not depend upon snapshots. 
Freeze snapshots to dated versions or set the LEIN_SNAPSHOTS_IN_RELEASE environment variable to override.
MacBook-Pro:clojush leespector$

**Comment by lspector** [comment]
Hmmm github mangled the transcript... but I hope you can see the issue... something about a dependency on a snapshot version of something...

In addition to fixing the underlying problem, please let me know how I should proceed from my current point of stuckness...

**Comment by thelmuth** [comment]
Ok, looks like the problem is that Clojuars doesn't let you include a dependency that has "SNAPSHOT" in it. I have no idea why. I have included `[danlentz/clj-uuid "0.1.2-SNAPSHOT"]` in the dependencies list in order to use the UUID library. I don't know what to do about this.

Looks like the requirements here might be why: http://bendb.com/how-to-deploy-to-clojars/

I guess the solution might be to stop using the UUID library, but that seems silly. Not sure what else to do.

**Comment by lspector** [comment]
I see a bunch of other libraries when I search clojars for uuid, but I don't know if any of them would suffice. Alternatively, maybe you could convince danlentz to release a non-snapshot version (presumably via https://github.com/danlentz/clj-uuid/).

FWIW I ran into this previously... and I think the idea is that snapshots aren't supposed to be stable...

**Pull request merged**
