### PR TITLE
[not ready] Document and Test Plush 

### LINKED ISSUE #128: Document Plush genomes and Push programs in the repo
I think you should have either (a) a Markdown document in the repo or (b) a repo wiki page that documents Plush genomes and Push programs. My inclination would be towards the former since then the docs are right in the code, but I'm open to other thoughts on the matter. 

This might be something I'd be willing to pick up as a semi-outsider.

### PR DESCRIPTION
**Pull request by saulshanabrook**
I am trying to document the rationale and mechanics of Plush genomes. My goals are to:

* Document the rationale behind them clearly enough that someone who understands Push but hasn't heard of them before will know why they exist and how they should use them.
* Document (both with words and tests) how they are implemented completely enough that someone who wants to re-implement them (*cough* @Vaguery *cough*) would be able to.

This would close #128

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Superceded by https://github.com/lspector/Clojush/pull/181

**Comment by Vaguery** [comment]
Is it "in the repo"?

**Comment by saulshanabrook** [comment]
@Vaguery  No, I closed it cause it looked like that wiki page had a more thorough description than mine. Do you see a good reason for me to merge this?

**Comment by Vaguery** [comment]
I guess I was suggesting you should bring the wiki page over from the discourse server when it looks done.

**Pull request closed without merging**
