### PR TITLE
Added uniform selection as a baseline. Also, removed meta-error from odd...

### PR DESCRIPTION
**Pull request by thelmuth**
... problem demo

### CODE REVIEW

**Comment by thelmuth** [comment]
Lee -- Would you be able to merge this soon? I know there are people from GPTP using Clojush, and this branch fixes some bugs that would be good to have squashed. Thanks!

**Comment by Vaguery** [comment]
Could I get a quick rundown on what "uniform selection" is? Is it what I would call "no" or "random" selection (that is, fitness-ignoring)?

**Comment by thelmuth** [comment]
Bill -- Yes, that is exactly what it is.

**Comment by lspector** [comment]
Merged in 2.0.25, along with a bunch of other stuff.

**Pull request merged**
