### PR TITLE
Remove nrepl port

### PR DESCRIPTION
**Pull request by thelmuth**
Lee - did you update your CCW recently? I just updated mine, and found that it now makes a file called .nrepl-port, which you included in a commit 17 days ago. Anyway, this pull request just removes that file and adds it to .gitignore.

### CODE REVIEW

**Comment by thelmuth** [comment]
Oh, I also changed Leaky Lexicase to use uniform selection instead of tournament selection with size = 1

**Comment by lspector** [comment]
Merged as 2.0.26. BTW if would be nice if the email notice that I received contained the branch name...

**Comment by thelmuth** [comment]
Does your email have something like this:

Reply to this email directly or view it on GitHub
<https://github.com/lspector/Clojush/pull/132#event-310149248>.

If so, branch names are at the top of that GitHub link.

**Comment by lspector** [comment]
Yes -- but that means that I have to follow the link to get that piece of needed information. Not a huge step, but one more in the dozen or so that I still really wish could be clicking one button. If the branch name was in the email then I could copy it from there and move right on to saving and closing buffers in CCW, getting a terminal and the instructions on the screen where I can see them both, and beginning to follow all of the instructions...

> On May 20, 2015, at 9:37 PM, Tom Helmuth <notifications@github.com> wrote:
> 
> Does your email have something like this:
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/lspector/Clojush/pull/132#event-310149248>.
> 
> If so, branch names are at the top of that GitHub link.
> 
> On Wed, May 20, 2015 at 9:33 PM, Lee Spector <notifications@github.com>
> wrote:
> 
> > Merged as 2.0.26. BTW if would be nice if the email notice that I received
> > contained the branch name...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lspector/Clojush/pull/132#issuecomment-104090400>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/pull/132#issuecomment-104090819>.
> 

--
Lee Spector, Professor of Computer Science
Director, Institute for Computational Intelligence
Cognitive Science, Hampshire College
893 West Street, Amherst, MA 01002-3359
lspector@hampshire.edu, http://hampshire.edu/lspector/
Phone: 413-559-5352, Fax: 413-559-5438

**Comment by thelmuth** [comment]
I'll try to include it in the future. Do you get the pull request messages in your email? I often include important communications in those.

**Comment by lspector** [comment]
Thanks,

Yes, I get the pull requests in email. I'll include the one I just got below. Lots of stuff in it, including your message, but not the branch name.

I'm again considering scripting the update process. It's just so mindless and error prone, takes a lot more time than it should, breaks the flow of whatever else I'm working on, etc.

 -Lee

Here's the pull request:

---

On May 20, 2015, at 8:38 PM, Tom Helmuth <notifications@github.com> wrote:

Lee - did you update your CCW recently? I just updated mine, and found that it now makes a file called .nrepl-port, which you included in a commit 17 days ago. Anyway, this pull request just removes that file and adds it to .gitignore.

You can view, comment on, or merge this pull request online at:

  https://github.com/lspector/Clojush/pull/132 <https://github.com/lspector/Clojush/pull/132>
Commit Summary

Removed .nrepl-port
Added .nrepl-port to .gitignore
File Changes

M .gitignore <https://github.com/lspector/Clojush/pull/132/files#diff-0> (1)
D .nrepl-port <https://github.com/lspector/Clojush/pull/132/files#diff-1> (1)
Patch Links:

https://github.com/lspector/Clojush/pull/132.patch <https://github.com/lspector/Clojush/pull/132.patch>
https://github.com/lspector/Clojush/pull/132.diff <https://github.com/lspector/Clojush/pull/132.diff>
—
Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/pull/132>.


> On May 20, 2015, at 9:45 PM, Tom Helmuth <notifications@github.com> wrote:
> 
> I'll try to include it in the future. Do you get the pull request messages in your email? I often include important communications in those.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/pull/132#issuecomment-104091530>.
> 

--
Lee Spector, Professor of Computer Science
Director, Institute for Computational Intelligence
Cognitive Science, Hampshire College
893 West Street, Amherst, MA 01002-3359
lspector@hampshire.edu, http://hampshire.edu/lspector/
Phone: 413-559-5352, Fax: 413-559-5438

**Comment by lspector** [comment]
Huh -- the pull request formatting got mangled by github... It doesn't look that weird in my email. In any event, it doesn't contain the branch name.

**Comment by thelmuth** [comment]
Good enough for me, thanks!

**Pull request merged**
