### PR TITLE
add inital docs for working with docker

### PR DESCRIPTION
**Pull request by saulshanabrook**

### CODE REVIEW

**Comment by lspector** [comment]
I think this is a most excellent addition, but I also think that the description is a bit too minimal for people who don't know what docker is, why they'd want to do this, or what they'd have to set up in order to make this work. Could you flesh it out a *little* more before we merge it? Not with deep discussions on all of that stuff, of course, but maybe with a sentence or two, and maybe a link or two, for orientation?

Also, the most appropriate place for this may be following the paragraph on IDEs, without a separate header. This is where other ways of running the system are briefly discussed. The Leiningen approach is first (and "documented" mostly just by pointing to leningen.org) because that's the most popular simple way to run Clojure programs. I do think we can assume some familiarity with the Clojure ecosystem if someone is trying to use this code.

**Comment by saulshanabrook** [comment]
@lspector Yep makes sense, will do.

**Comment by saulshanabrook** [comment]
@lspector How does it look now?

**Comment by lspector** [comment]
Looks good. Merged.

**Pull request merged**
