### PR TITLE
updated all project dependencies flagged by 'lein ancient', including clojure

### PR DESCRIPTION
**Pull request by Vaguery**
Also: I **did not** bump the version number; that I assume is up to you.

### CODE REVIEW

**Comment by Vaguery** [comment]
What are the Travis-CI checks that are failing?

**Comment by Shalmezad** [comment]
@Vaguery [SSL certificate error](https://travis-ci.org/lspector/Clojush/builds/496553838#L571) near as I can tell.

Would recommend either trying to update the certs (build says "This is often caused by an out-of-date version of libssl." so could try updating that in the before_script or trying any of the commands [here](https://github.com/technomancy/leiningen/issues/1634))

or using a later distribution like xenial which might also do the trick (add `dist: xenial` in travis.yml [like so](https://github.com/michaelklishin/monger/blob/master/.travis.yml)) since it's currently using trusty as the base image which is going to be EOL in april of this year.

**Comment by Vaguery** [comment]
Oh good grief. It's trying to download a `lein` standalone and failing. Huh.

**Comment by Vaguery** [comment]
This gets bumped up I suppose.

**Comment by Shalmezad** [comment]
Looks like xenial will get you past the ssl issue, but you'll run into another one. Appears to be clojure specific, so can't help there. 
Travis: https://travis-ci.org/Shalmezad/Clojush/builds/496633280
Commit: https://github.com/Shalmezad/Clojush/commit/edbaea97847b1e4bae51e1f87282c9a7c44fd1ab

**Comment by Vaguery** [comment]
[I've updated the plugin dependencies as well; it compiles on my local Open-JDK 11 install.

**Comment by Vaguery** [comment]
Apparently the problem arose from a bad `:plugin` setting, which I hadn't updated.

**Pull request merged**
