### PR TITLE
Refactor/some simple things

### PR DESCRIPTION
**Pull request by thelmuth**
I'm pretty sure the tournament selection code does the same thing, but @lspector should double check.

### CODE REVIEW

**Comment by lspector** [comment]
The tournament selection code looks fine to me, but I'm uneasy about this, since `cons` always adds to the front, while `conj` sometimes adds to the end, depending on the type of collection it is passed,  and I'm not sure that everything in the project maintains the types of stacks in a way that will ensure that `conj` always does what we want. Are you sure?

```
-  (assoc state type (cons value (type state))))
 +  (update state type conj value))
```

**Comment by thelmuth** [comment]
I am definitely **not** sure! I had assumed stacks were always lists, but maybe that's not always the case. We can not apply that change if it seems potentially problematic.

**Comment by lspector** [comment]
Let's do it without that change then. It may be fine but because of this issue I tend to use `conj` only when I'm certain what type I'm dealing with *or* I know that order doesn't matter (not true for stacks).

Can you re-submit without this?

**Comment by thelmuth** [comment]
Agreed. I am, however, just going to merge the other two changes into my novelty/behaviors branch that I just finished and will make a pull request shortly.

**Pull request closed without merging**
